import type {
  Garment,
  Outfit,
  PersonaOutfit,
  SizeProfile,
  StylePersona,
  UserStyleProfile,
} from "@/types";
import personasData from "@/data/personas.json";

// Coherent, hand-authored dataset that lets every hero flow run end to end
// with zero API credentials. Demo Mode never pretends this came from a live
// call — the UI always labels it "Demo Mode".

export const DEMO_STYLE_PROFILE: UserStyleProfile = {
  styleWeights: {
    minimal: 0.7,
    streetwear: 0.55,
    workwear: 0.85,
    vintage: 0.6,
    contemporary: 0.5,
  },
  favoriteColors: ["brown", "cream", "black", "white"],
  avoidedColors: ["neon"],
  preferredFit: "relaxed",
  notes: "Comfortable in earth tones, likes texture, avoids anything too fitted.",
  discoveredAt: new Date("2026-08-20").toISOString(),
};

export const DEMO_SIZE_PROFILE: SizeProfile = {
  sizingSystem: "US",
  tops: "M",
  bottoms: "32",
  waist: "32",
  inseam: "30",
  jeans: "32x30",
  shoes: "10.5",
  preferredFit: "relaxed",
};

const now = new Date("2026-09-05").toISOString();

export const DEMO_RESCUE_ITEM: Garment = {
  id: "demo_rescue_overshirt",
  image: "",
  name: "Brown Corduroy Overshirt",
  category: "outerwear",
  subcategory: "overshirt",
  primaryColor: "warm brown",
  secondaryColors: [],
  material: "corduroy",
  pattern: "solid",
  fit: "relaxed",
  silhouette: "boxy",
  formality: 3,
  styleTags: ["workwear", "vintage", "americana"],
  seasonality: ["fall", "winter", "spring"],
  observations:
    "A heavier-weight corduroy overshirt with a classic boxy cut. The texture reads vintage, which pairs beautifully against clean, modern basics.",
  confidence: 0.91,
  addedAt: now,
  isRescueItem: true,
  rescueReason: "It feels too old-fashioned.",
};

export const DEMO_CLOSET: Garment[] = [
  {
    id: "demo_g_white_tee",
    image: "",
    name: "White Heavyweight Tee",
    category: "top",
    subcategory: "t-shirt",
    primaryColor: "white",
    secondaryColors: [],
    material: "heavyweight cotton",
    pattern: "solid",
    fit: "regular",
    silhouette: "boxy",
    formality: 1,
    styleTags: ["minimal", "contemporary", "streetwear"],
    seasonality: ["spring", "summer", "fall"],
    observations: "A clean, sturdy white tee that works as a base layer under almost anything.",
    confidence: 0.95,
    addedAt: now,
  },
  {
    id: "demo_g_black_jeans",
    image: "",
    name: "Black Straight-Leg Jeans",
    category: "bottom",
    subcategory: "jeans",
    primaryColor: "black",
    secondaryColors: [],
    material: "denim",
    pattern: "solid",
    fit: "regular",
    silhouette: "straight-leg",
    formality: 2,
    styleTags: ["minimal", "classic", "contemporary"],
    seasonality: ["fall", "winter", "spring"],
    observations: "Versatile straight-leg black denim, a reliable neutral bottom.",
    confidence: 0.94,
    addedAt: now,
  },
  {
    id: "demo_g_cream_trousers",
    image: "",
    name: "Cream Tailored Trousers",
    category: "bottom",
    subcategory: "trousers",
    primaryColor: "cream",
    secondaryColors: [],
    material: "cotton twill",
    pattern: "solid",
    fit: "relaxed",
    silhouette: "straight-leg",
    formality: 3,
    styleTags: ["workwear", "classic", "contemporary"],
    seasonality: ["spring", "summer", "fall"],
    observations: "Relaxed tailored trousers in a warm neutral, dresses up easily.",
    confidence: 0.9,
    addedAt: now,
  },
  {
    id: "demo_g_white_sneakers",
    image: "",
    name: "White Leather Sneakers",
    category: "footwear",
    subcategory: "sneaker",
    primaryColor: "white",
    secondaryColors: [],
    material: "leather",
    pattern: "solid",
    fit: "regular",
    silhouette: "low-top",
    formality: 2,
    styleTags: ["minimal", "contemporary", "classic"],
    seasonality: ["spring", "summer", "fall"],
    observations: "Clean low-top leather sneakers that modernize almost any outfit.",
    confidence: 0.93,
    addedAt: now,
  },
  {
    id: "demo_g_brown_boots",
    image: "",
    name: "Dark Brown Boots",
    category: "footwear",
    subcategory: "boot",
    primaryColor: "dark brown",
    secondaryColors: [],
    material: "leather",
    pattern: "solid",
    fit: "regular",
    silhouette: "ankle boot",
    formality: 3,
    styleTags: ["workwear", "vintage", "americana"],
    seasonality: ["fall", "winter"],
    observations: "Sturdy leather boots with a slightly worn-in, vintage character.",
    confidence: 0.92,
    addedAt: now,
  },
  {
    id: "demo_g_cream_cardigan",
    image: "",
    name: "Cream Cardigan",
    category: "top",
    subcategory: "cardigan",
    primaryColor: "cream",
    secondaryColors: [],
    material: "knit wool",
    pattern: "solid",
    fit: "regular",
    silhouette: "relaxed",
    formality: 2,
    styleTags: ["preppy", "classic", "contemporary"],
    seasonality: ["fall", "winter", "spring"],
    observations: "A soft knit cardigan that layers well over collared shirts or tees.",
    confidence: 0.9,
    addedAt: now,
  },
  {
    id: "demo_g_green_cap",
    image: "",
    name: "Green Cap",
    category: "headwear",
    subcategory: "baseball cap",
    primaryColor: "green",
    secondaryColors: [],
    material: "cotton twill",
    pattern: "solid",
    fit: "regular",
    silhouette: "structured",
    formality: 1,
    styleTags: ["streetwear", "sporty", "relaxed"],
    seasonality: ["spring", "summer", "fall"],
    observations: "A structured cap that adds a casual, sporty accent to an outfit.",
    confidence: 0.88,
    addedAt: now,
  },
];

export const DEMO_FULL_CLOSET: Garment[] = [DEMO_RESCUE_ITEM, ...DEMO_CLOSET];

export const DEMO_RESCUE_OUTFITS: Outfit[] = [
  {
    id: "demo_outfit_coffee_shop_creative",
    name: "Coffee Shop Creative",
    vibe: "Modern workwear with a soft edge",
    garmentIds: ["demo_rescue_overshirt", "demo_g_white_tee", "demo_g_black_jeans", "demo_g_white_sneakers"],
    explanation:
      "You said the overshirt feels old-fashioned, so this combination leans on clean, contemporary basics — a plain white tee, straight black denim, and white sneakers — to modernize it while keeping the texture that makes the corduroy interesting.",
    stylingNotes: [
      "Leave the overshirt open over the tee rather than buttoned",
      "Roll the cuffs once to show a little wrist",
      "Keep the sneakers box-fresh looking to balance the vintage texture",
    ],
    occasion: "Everyday / coffee run",
    colorHarmony: "Warm brown against black and white keeps the palette simple and current.",
    trendIds: ["trend_modern-workwear"],
    confidenceScore: 0.92,
    optionalTweak: "Swap in a thin gold chain if you want a touch more polish.",
    missingPieces: [],
    lane: "safe",
  },
  {
    id: "demo_outfit_workwear_remix",
    name: "Workwear Remix",
    vibe: "Textured layering, elevated basics",
    garmentIds: ["demo_rescue_overshirt", "demo_g_cream_cardigan", "demo_g_cream_trousers", "demo_g_brown_boots"],
    explanation:
      "Instead of hiding the vintage feel, this look leans into it — cream trousers and boots pull warmth from the overshirt, while the cardigan underneath adds a soft, unexpected layer so it doesn't read as costume-y.",
    stylingNotes: [
      "Layer the cardigan under the overshirt, buttoned at the chest only",
      "Cuff the trousers to show the boots",
    ],
    occasion: "Weekend / casual dinner",
    colorHarmony: "All-tonal browns and creams read intentional rather than mismatched.",
    trendIds: ["trend_chocolate-brown-tonal-dressing", "trend_quiet-luxury-cashmere-knits"],
    confidenceScore: 0.88,
    missingPieces: [],
    lane: "current",
  },
  {
    id: "demo_outfit_street_layer",
    name: "Street Layer",
    vibe: "Relaxed streetwear with a workwear anchor",
    garmentIds: ["demo_rescue_overshirt", "demo_g_white_tee", "demo_g_black_jeans", "demo_g_green_cap", "demo_g_white_sneakers"],
    explanation:
      "The cap and sneakers pull the overshirt toward streetwear territory, which is a bigger departure from how you've worn it before — but the black denim keeps it grounded so it still feels like you.",
    stylingNotes: [
      "Wear the cap slightly back for a relaxed feel",
      "Leave one button open at the collar",
    ],
    occasion: "Casual weekend",
    colorHarmony: "A single green accent against brown, black, and white keeps it playful but controlled.",
    trendIds: ["trend_skate-influenced-streetwear"],
    confidenceScore: 0.83,
    optionalTweak: "This is your most experimental option of the three — try it once before committing.",
    missingPieces: [],
    lane: "push-me",
  },
];

export const DEMO_STYLE_NOW_OUTFITS: Outfit[] = [
  {
    id: "demo_style_now_safe",
    name: "Easy Everyday",
    vibe: "Reliable, clean basics",
    garmentIds: ["demo_g_white_tee", "demo_g_black_jeans", "demo_g_white_sneakers"],
    explanation:
      "This is the most naturally-you combination in your closet — clean basics you already reach for, with nothing that asks you to think twice.",
    stylingNotes: ["Keep the tee untucked", "Cuff the jeans once above the sneaker"],
    occasion: "Everyday",
    colorHarmony: "Black and white keep it simple and versatile.",
    trendIds: [],
    confidenceScore: 0.95,
    missingPieces: [],
    lane: "safe",
  },
  {
    id: "demo_style_now_current",
    name: "Tonal Brown Layer",
    vibe: "This season's warm neutrals",
    garmentIds: ["demo_g_cream_cardigan", "demo_g_white_tee", "demo_g_cream_trousers", "demo_g_brown_boots"],
    explanation:
      "Chocolate-brown tonal dressing is one of the strongest signals on your Trend Radar right now, and this combination builds it entirely from pieces you already own.",
    stylingNotes: ["Layer the cardigan open over the tee", "Cuff the trousers to show the boots"],
    occasion: "Everyday",
    colorHarmony: "Tonal cream and brown reads intentional, not mismatched.",
    trendIds: ["trend_chocolate-brown-tonal-dressing"],
    confidenceScore: 0.87,
    missingPieces: [],
    lane: "current",
  },
  {
    id: "demo_style_now_push",
    name: "Cap & Cardigan",
    vibe: "A playful streetwear accent",
    garmentIds: ["demo_g_green_cap", "demo_g_cream_cardigan", "demo_g_white_tee", "demo_g_black_jeans", "demo_g_white_sneakers"],
    explanation:
      "A bigger departure from your usual rotation — the cap pulls this toward streetwear, while the cardigan and black denim keep it grounded enough to actually wear.",
    stylingNotes: ["Wear the cap slightly back", "Leave the cardigan open over the tee"],
    occasion: "Everyday",
    colorHarmony: "One green accent against neutral basics keeps it playful but controlled.",
    trendIds: ["trend_dopamine-color-palettes"],
    confidenceScore: 0.79,
    optionalTweak: "Your most experimental option today — try it once before committing.",
    missingPieces: [],
    lane: "push-me",
  },
];

export const DEMO_PERSONA: StylePersona = (personasData as StylePersona[]).find(
  (p) => p.id === "persona_tyler_the_creator"
)!;

export const DEMO_PERSONA_OUTFITS: PersonaOutfit[] = [
  {
    id: "demo_persona_outfit_closet",
    name: "Colorful Prep",
    vibe: "Your closet, Tyler-tinted",
    garmentIds: ["demo_g_cream_cardigan", "demo_g_white_tee", "demo_g_cream_trousers", "demo_g_white_sneakers"],
    explanation:
      "Almost entirely from your own closet — the cardigan and cream trousers already carry the preppy, textured energy Tyler leans on, so this needed almost no help.",
    stylingNotes: ["Layer the cardigan over the tee, left unbuttoned", "Cuff the trousers to show a little ankle"],
    occasion: "Everyday",
    colorHarmony: "Cream and white keep it light, exactly the kind of clean-but-playful palette he favors.",
    trendIds: [],
    confidenceScore: 0.86,
    missingPieces: [],
    lane: "closet",
    whyThisFeelsLikeThem: [
      "relaxed trouser proportions",
      "knitwear worn as the statement piece, not an afterthought",
      "clean, light palette instead of logos",
    ],
    styleSimilarity: { silhouette: 82, colorLanguage: 74, layering: 88, footwear: 70, accessories: 40 },
    overallSimilarity: 76,
  },
  {
    id: "demo_persona_outfit_current",
    name: "Tyler × Modern Prep",
    vibe: "Preppy, but with this season's brown",
    garmentIds: ["demo_g_cream_cardigan", "demo_rescue_overshirt", "demo_g_cream_trousers", "demo_g_brown_boots"],
    explanation:
      "Pairing the cardigan with the corduroy overshirt gives the same boxy-on-top layering he's known for, while the current tonal-brown trend keeps it feeling like this season rather than a throwback.",
    stylingNotes: ["Layer overshirt open over the cardigan", "Let the boots anchor the warm palette"],
    occasion: "Weekend / casual gathering",
    colorHarmony: "Tonal browns and cream connect directly to this season's chocolate-brown trend.",
    trendIds: ["trend_chocolate-brown-tonal-dressing"],
    confidenceScore: 0.85,
    missingPieces: [],
    lane: "current",
    whyThisFeelsLikeThem: [
      "boxy layered proportions",
      "texture mixing (corduroy + knit) over pattern",
      "warm, vintage-leaning palette",
    ],
    styleSimilarity: { silhouette: 88, colorLanguage: 80, layering: 90, footwear: 65, accessories: 35 },
    overallSimilarity: 80,
  },
  {
    id: "demo_persona_outfit_full_send",
    name: "Golf-Course Maximalist",
    vibe: "Full send on the preppy-playful energy",
    garmentIds: ["demo_g_green_cap", "demo_g_cream_cardigan", "demo_g_white_tee", "demo_g_black_jeans", "demo_g_white_sneakers"],
    explanation:
      "This is the most expressive read — the cap does a lot of the work here, standing in for the bucket hats and bold accessories he's rarely without, while everything else stays wearable.",
    stylingNotes: ["Wear the cap forward, not backward", "Leave the cardigan fully open over the tee"],
    occasion: "Fashion event / casual outing",
    colorHarmony: "One accent color (green) against a light neutral base mirrors his color-blocking habit.",
    trendIds: ["trend_dopamine-color-palettes"],
    confidenceScore: 0.78,
    optionalTweak: "A pair of colorful socks would push this even further if you have them.",
    missingPieces: ["a bucket hat would push this closer to his signature silhouette"],
    lane: "full-send",
    whyThisFeelsLikeThem: [
      "unexpected accent color used deliberately",
      "boxy, relaxed proportions throughout",
      "playful accessory as the focal point",
    ],
    styleSimilarity: { silhouette: 75, colorLanguage: 85, layering: 70, footwear: 60, accessories: 82 },
    overallSimilarity: 74,
  },
];

export const DEMO_STYLIST_STEPS: string[] = [
  "Start with the white tee.",
  "Add the brown corduroy overshirt over it.",
  "Leave the top two buttons open.",
  "Roll each sleeve once.",
  "Step into the black straight-leg jeans.",
  "Slide on the white sneakers.",
  "Great — step back so I can see the full outfit.",
];

export const DEMO_FINAL_CRITIQUE = {
  critique:
    "The relaxed proportions work well together. Opening the overshirt creates more vertical structure and keeps a texture-heavy piece feeling current instead of costume-y.",
  strengths: [
    "Clean contrast between the boxy overshirt and slim denim",
    "Sneakers keep the whole look grounded and modern",
  ],
  suggestion: "Try tucking just the front of the tee for a little more shape.",
};
